version: '2'
services:
  db:
    environment:
      MYSQL_DATABASE: beefme
      MYSQL_PASSWORD: beef
      MYSQL_ROOT_PASSWORD: beef
      MYSQL_USER: beef
    ports: 
      - 3306:3306
    image: mysql:5.7      
